// <auto-generated />
using System;
using Evote360.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VoteContext))]
    [Migration("20251014205119_ElectionCandidateTableAdded")]
    partial class ElectionCandidateTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Evote360.Core.Domain.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.CandidatePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("CandidatePositions", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Elections", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("ElectionCandidates", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("ElectionId", "PoliticalPartyId")
                        .IsUnique();

                    b.ToTable("ElectionParty", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("ElectionId", "ElectivePositionId")
                        .IsUnique();

                    b.ToTable("ElectionPosition", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ElectivePositions", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.PartyLeaderAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PartyLeaderAssignments", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestingPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TargetPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetPartyId");

                    b.HasIndex("RequestingPartyId", "TargetPartyId");

                    b.ToTable("PoliticalAlliances", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VoteDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("CitizenId", "ElectionId", "ElectivePositionId")
                        .IsUnique();

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoPath")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("PoliticalParty", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "PoliticalParty")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.CandidatePosition", b =>
                {
                    b.HasOne("Evote360.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionCandidate", b =>
                {
                    b.HasOne("Evote360.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.Election", "Election")
                        .WithMany("ElectionCandidates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Election");

                    b.Navigation("ElectivePosition");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionParty", b =>
                {
                    b.HasOne("Evote360.Core.Domain.Entities.Election", "Election")
                        .WithMany("ElectionParties")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectionPosition", b =>
                {
                    b.HasOne("Evote360.Core.Domain.Entities.Election", "Election")
                        .WithMany("ElectionPositions")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.PartyLeaderAssignment", b =>
                {
                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "PoliticalParty")
                        .WithMany("Leaders")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Evote360.Core.Domain.Entities.PartyLeaderAssignment", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.PoliticalAlliance", b =>
                {
                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "RequestingParty")
                        .WithMany("RequestAlliances")
                        .HasForeignKey("RequestingPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.PoliticalParty", "TargetParty")
                        .WithMany("TargetAlliances")
                        .HasForeignKey("TargetPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestingParty");

                    b.Navigation("TargetParty");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Evote360.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Evote360.Core.Domain.Citizen", "Citizen")
                        .WithMany("Votes")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evote360.Core.Domain.Entities.ElectivePosition", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Citizen");

                    b.Navigation("Election");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Citizen", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("CandidatePositions");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.Election", b =>
                {
                    b.Navigation("ElectionCandidates");

                    b.Navigation("ElectionParties");

                    b.Navigation("ElectionPositions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Evote360.Core.Domain.Entities.ElectivePosition", b =>
                {
                    b.Navigation("CandidatePositions");
                });

            modelBuilder.Entity("Evote360.Core.Domain.PoliticalParty", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Leaders");

                    b.Navigation("RequestAlliances");

                    b.Navigation("TargetAlliances");
                });
#pragma warning restore 612, 618
        }
    }
}
